---
title: "Leaflet_Assignment"
author: "Manish patwal"
date: "14 October 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Background
In this leaflet assignment I will be showing top ten places to visit around pune as per the TripAdvisor Rating
https://www.tripadvisor.in/Attractions-g297654-Activities-Pune_Pune_District_Maharashtra.html#ATTRACTION_SORT_WRAPPER

#Load Libraries
```{r, message=FALSE}
library(leaflet)
library(dplyr)

```

#DataFrame Creation
Lets create a dataframe for the top 10 places with the lat and long.
```{r, message=FALSE}
toptentripadvisor <- data.frame(name = c("National Defence Academy", "Dagadusheth Halwai Ganapati Temple", "Darshan Museum","ISKCON NVCC Temple", "Western Ghats","Malshej Ghats", "Rajgad Fort", "Narayani Dham Temple","Sri Balaji Mandir","Ranjangaon Ganpati Temple"),lat = c(18.4703,18.5164,18.5236,18.4478,18.3102, 19.3406,18.2467,18.7635,18.5416,18.7534),lng = c(73.7745,73.8561,73.8768, 73.8807, 73.7746, 73.7746,73.6823,73.4132,73.7898,74.2406))
head(toptentripadvisor)
```

#Adding Map
```{r, message=FALSE}
toptentripadvisor %>% leaflet() %>% addTiles() %>%  addCircleMarkers(weight=2,popup = c("National Defence Academy", "Dagadusheth Halwai Ganapati Temple","Darshan Museum","ISKCON NVCC Temple","Western Ghats","Malshej Ghats", "Rajgad Fort", "Narayani Dham Temple", "Sri  Balaji Mandir","Ranjangaon Ganpati  Temple"), color="green") %>% addLegend(labels = c("National Defence Academy", "Dagadusheth Halwai Ganapati Temple", "Darshan Museum", "ISKCON NVCC Temple","Western Ghats","Malshej Ghats", "Rajgad Fort", "Narayani Dham Temple", "Sri Balaji Mandir","Ranjangaon Ganpati Temple"), colors=toptentripadvisor$name)
```

Now go pack your bags and visit these places.